# Generated by Django 5.0.6 on 2024-06-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="The entities label or name.",
                        max_length=100,
                    ),
                ),
                (
                    "label_type",
                    models.CharField(
                        blank=True, help_text="The type of the label.", max_length=255
                    ),
                ),
                (
                    "isocode",
                    models.CharField(
                        blank=True,
                        help_text="The ISO 639-3 code for the label's language.",
                        max_length=3,
                    ),
                ),
            ],
        ),
    ]
